"""
APK and AAB Packaging Engine for Storm Build 2026.
Fully automated pipeline mimicking official Android Gradle Plugin (AGP):
 - Resolves Maven transitives (parent POM / BOM / version ranges) on every build
 - Auto-harvests proguard.txt from all AAR dependencies
 - Auto-generates aapt_rules.txt from AAPT2
 - Generates R.java for every library package found in classes.jar
 - Injects CrashApplication so ContentProvider crashes (Yandex Ads) are logged
 - Rebuilds the APK from scratch (never appends to an aapt2 zip — that produced
   silent launch crashes with no stacktrace)
 - Packages native .so, assets and META-INF/services
"""

import os
import shutil
import zipfile
import subprocess
from pathlib import Path
from typing import List, Dict, Optional, Any, Set

from .env import Toolchain, Colors
from .progress import print_step
from .config import ProjectConfig
from .merger import ManifestMerger
from .deps import DependencyManager
from .compiler import Compiler
from .dexer import Dexer
from .signer import Signer
from .zipalign import align_apk, verify_alignment
from .crash_handler import generate_crash_handler_sources
from .icons import ensure_launcher_icon
from .apk_check import print_apk_report

DEFAULT_BASE_PROGUARD = """# ==============================================================================
# Standard Android SDK Base Rules (Auto-generated by Storm Build 2026)
# ==============================================================================

-keepattributes *Annotation*,Signature,InnerClasses,EnclosingMethod,Exceptions,SourceFile,LineNumberTable
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}

-keep public class * extends android.app.Activity
-keep public class * extends android.app.Application
-keep public class * extends android.app.Service
-keep public class * extends android.content.BroadcastReceiver
-keep public class * extends android.content.ContentProvider
-keep public class * extends android.app.backup.BackupAgentHelper
-keep public class * extends android.preference.Preference
-keep public class * extends androidx.startup.Initializer

-keep class com.storm.engine.crash.** { *; }

-keepclasseswithmembers class * {
    public <init>(android.content.Context, android.util.AttributeSet);
}
-keepclasseswithmembers class * {
    public <init>(android.content.Context, android.util.AttributeSet, int);
}

-keepclasseswithmembernames class * {
    native <methods>;
}

-keepclassmembers enum * {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

-keepclassmembers class * implements android.os.Parcelable {
    public static final ** CREATOR;
}

-keep class kotlin.** { *; }
-keep class kotlinx.** { *; }
-keep class com.yandex.** { *; }
-keep class io.appmetrica.** { *; }
-keep class androidx.startup.** { *; }

-dontwarn javax.annotation.**
-dontwarn javax.inject.**
-dontwarn org.checkerframework.**
-dontwarn org.jetbrains.annotations.**
-dontwarn kotlin.jvm.internal.SourceDebugExtension

# Compile-only annotations referenced by Play Services / Ads (not shipped in the APK)
-dontwarn com.google.errorprone.annotations.**
-dontwarn com.google.android.apps.common.proguard.**
-dontwarn com.google.android.gms.common.util.VisibleForTesting
-dontwarn org.codehaus.mojo.animal_sniffer.**
"""


class Packager:
    def __init__(self, config: ProjectConfig, toolchain: Toolchain):
        self.config = config
        self.toolchain = toolchain
        self.root_dir = config.root_dir
        self.build_dir = self.root_dir / "build"
        self.outputs_dir = self.build_dir / "outputs"

    def clean(self):
        """Remove all build artifacts."""
        if self.build_dir.exists():
            shutil.rmtree(str(self.build_dir))
            print("  [CLEAN] Removed build/ directory.")

    def compile_resources(self, aapt2: str, res_dirs: List[Path], out_compiled_dir: Path) -> List[Path]:
        """Compile each resource folder to a .zip (avoids ARG_MAX on aapt2 link)."""
        if out_compiled_dir.exists():
            shutil.rmtree(str(out_compiled_dir))
        out_compiled_dir.mkdir(parents=True, exist_ok=True)
        compiled_files: List[Path] = []

        for idx, rdir in enumerate(res_dirs):
            if not rdir.exists() or not any(rdir.iterdir()):
                continue

            zip_out = out_compiled_dir / f"res_{idx}_{rdir.parent.name}.zip"
            print(f"  [AAPT2] Compiling resources from: {rdir.parent.name}/res...")
            cmd = [aapt2, "compile", "--dir", str(rdir), "-o", str(zip_out)]
            res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            if res.returncode == 0 and zip_out.exists() and zip_out.stat().st_size > 0:
                compiled_files.append(zip_out)
                continue

            # Older aapt2: compile into a directory of .flat files.
            sub_compiled = out_compiled_dir / f"res_{idx}_{rdir.parent.name}"
            sub_compiled.mkdir(parents=True, exist_ok=True)
            cmd = [aapt2, "compile", "--dir", str(rdir), "-o", str(sub_compiled)]
            res = subprocess.run(cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
            if res.returncode != 0:
                print(f"[ERROR] AAPT2 compile failed for {rdir}:\n{res.stderr}")
                return []

        if not compiled_files:
            for flat in sorted(out_compiled_dir.rglob("*.flat")):
                compiled_files.append(flat)

        return compiled_files

    def _require_tools(self, need_bundletool: bool = False) -> Optional[Dict[str, Any]]:
        aapt2 = self.toolchain.get_aapt2()
        needed_api = max(int(self.config.compile_sdk or 34), int(self.config.target_sdk or 34))
        print(f"  [SDK] Checking android.jar API {needed_api} "
              f"(compileSdk={self.config.compile_sdk}, targetSdk={self.config.target_sdk})")
        android_jar_str = self.toolchain.ensure_android_jar(needed_api, download=True)
        javac_bin, comp_type = self.toolchain.get_java_compiler()
        dexer_bin, dexer_type = self.toolchain.get_dexer()
        signer_bin, signer_type = self.toolchain.get_apksigner()

        if not aapt2:
            print(f"{Colors.RED}[ERROR] aapt2 not found. Run 'storm doctor' or 'storm setup'.{Colors.RESET}")
            return None
        if not android_jar_str or not Path(android_jar_str).exists():
            print(f"{Colors.RED}[ERROR] android.jar (API {needed_api}) not found and download failed.{Colors.RESET}")
            print(f"        Check internet, then retry `storm build apk` (or `storm setup --api {needed_api}`).")
            return None

        aapt2, link_jar, compile_jar = self.toolchain.resolve_platform_jars(
            aapt2, Path(android_jar_str), needed_api
        )
        if not aapt2:
            print(f"{Colors.RED}[ERROR] aapt2 not found after SDK check.{Colors.RESET}")
            return None

        if not javac_bin:
            print(f"{Colors.RED}[ERROR] Java compiler (javac / ecj) not found.{Colors.RESET}")
            return None
        if not dexer_bin:
            print(f"{Colors.RED}[ERROR] Dexer (d8 / r8 / d8.jar) not found.{Colors.RESET}")
            return None
        bundletool = None
        if need_bundletool:
            bundletool = self.toolchain.get_bundletool()
            if not bundletool:
                print(f"{Colors.RED}[ERROR] bundletool not found. Run 'storm setup' to download bundletool.jar.{Colors.RESET}")
                return None

        return {
            "aapt2": aapt2,
            "android_jar": compile_jar,
            "link_jar": link_jar,
            "javac_bin": javac_bin,
            "comp_type": comp_type,
            "dexer_bin": dexer_bin,
            "dexer_type": dexer_type,
            "signer_bin": signer_bin,
            "signer_type": signer_type,
            "bundletool": bundletool,
        }

    def _prepare_code_and_resources(self, tools: Dict[str, Any], proto: bool, use_r8: bool, release: bool) -> Optional[Dict[str, Any]]:
        aapt2 = tools["aapt2"]
        android_jar = tools["android_jar"]
        link_jar = tools.get("link_jar") or android_jar

        gen_dir = self.build_dir / "gen"
        res_compiled_dir = self.build_dir / "res_compiled"
        classes_dir = self.build_dir / "classes"
        dex_dir = self.build_dir / "dex"
        merged_manifest_dir = self.build_dir / "merged_manifest"
        aapt_rules_path = self.build_dir / "aapt_rules.txt"
        base_rules_path = self.build_dir / "base_proguard_rules.txt"

        ensure_launcher_icon(self.root_dir, self.config.res_dirs)

        print_step(1, 7, "Preparing Dependencies & AARs",
                   "cache ~/.storm/cache  ·  lock storm.lock")
        dep_mgr = DependencyManager(str(self.root_dir), self.config.repositories)
        refresh = bool(getattr(self, "refresh_deps", False))
        deps_data = dep_mgr.prepare_all_dependencies(
            self.config.dependencies, resolve=True, refresh=refresh
        )
        if self.config.dependencies and not deps_data.get("ok", True):
            print(f"{Colors.RED}[ERROR] Could not fetch project dependencies. "
                  f"Build stopped before compile.{Colors.RESET}")
            return None

        report_path = self.build_dir / "resolved-deps.txt"
        report_path.parent.mkdir(parents=True, exist_ok=True)
        with open(report_path, "w", encoding="utf-8") as f:
            f.write(f"# Storm Build 2026 resolved dependencies for {self.config.package}\n")
            for key, info in sorted((deps_data.get("resolved") or {}).items()):
                f.write(f"{info.get('group')}:{info.get('artifact')}:{info.get('version')}@{info.get('ext')}\n")
            f.write(f"\n# jars: {len(deps_data['jars'])}\n")
            f.write(f"# res dirs: {len(deps_data['res_dirs'])}\n")
            f.write(f"# extra packages: {', '.join(deps_data.get('extra_packages') or [])}\n")
        print(f"  [DEPS] Resolution report: {report_path}")

        print(f"\n{Colors.CYAN}[2/7] Merging Android Manifests...{Colors.RESET}")
        merger = ManifestMerger(str(self.config.manifest_path), self.config.package)
        for aar_man in deps_data["manifests"]:
            merger.merge_aar_manifest(str(aar_man))

        merged_manifest_path = merged_manifest_dir / "AndroidManifest.xml"
        merger.save(
            str(merged_manifest_path),
            min_sdk=self.config.min_sdk,
            target_sdk=self.config.target_sdk,
        )
        print(f"  [MANIFEST] uses-sdk minSdk={self.config.min_sdk} targetSdk={self.config.target_sdk}")
        if merger.user_application_class:
            print(f"  [MANIFEST] Wrapping Application {merger.user_application_class} with CrashApplication")
        else:
            print("  [MANIFEST] Injected com.storm.engine.crash.CrashApplication")

        print(f"\n{Colors.CYAN}[3/7] Compiling & Linking Resources (AAPT2)...{Colors.RESET}")
        all_res_dirs = self.config.res_dirs + deps_data["res_dirs"]
        compiled = self.compile_resources(aapt2, all_res_dirs, res_compiled_dir)

        gen_dir.mkdir(parents=True, exist_ok=True)
        linked = self.build_dir / ("proto_base.zip" if proto else "base.apk")
        print(f"  [AAPT2] -I {Path(link_jar).name}  ·  javac {Path(android_jar).name}")
        link_cmd = [
            aapt2, "link",
            "-I", str(link_jar),
            "--manifest", str(merged_manifest_path),
            "--java", str(gen_dir),
            "--custom-package", self.config.package,
            "--proguard", str(aapt_rules_path),
            "--min-sdk-version", str(self.config.min_sdk),
            "--target-sdk-version", str(self.config.target_sdk),
            "--version-code", str(self.config.version_code),
            "--version-name", self.config.version_name,
            "--auto-add-overlay",
            "-o", str(linked),
        ]
        if proto:
            link_cmd.append("--proto-format")

        extra_pkgs = [p for p in deps_data.get("extra_packages", []) if p and p != self.config.package]
        if extra_pkgs:
            extra_pkgs_str = ":".join(extra_pkgs)
            print(f"  [AAPT2] Generating R.java for {len(extra_pkgs)} library packages")
            link_cmd.extend(["--extra-packages", extra_pkgs_str])

        link_cmd.extend([str(f) for f in compiled])

        # Prefer an @argfile when the command is huge.
        if len(link_cmd) > 200:
            argfile = self.build_dir / "aapt2.link.args"
            with open(argfile, "w", encoding="utf-8") as f:
                for item in link_cmd[1:]:
                    f.write(item + "\n")
            link_res = subprocess.run([aapt2, f"@{argfile}"], stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        else:
            link_res = subprocess.run(link_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        if link_res.returncode != 0:
            print(f"[ERROR] AAPT2 link failed:\n{link_res.stderr}")
            return None

        print(f"\n{Colors.CYAN}[4/7] Compiling sources ({tools['comp_type']})...{Colors.RESET}")
        generate_crash_handler_sources(gen_dir, self.config.src_dirs, merger.user_application_class)
        has_kt = any(d.exists() and any(d.rglob("*.kt")) for d in self.config.src_dirs)
        kotlinc = None
        kstd = []
        if has_kt:
            kotlinc = self.toolchain.ensure_kotlinc(download=True)
            kstd = self.toolchain.kotlin_stdlib_jars()
        compiler = Compiler(
            tools["javac_bin"],
            tools["comp_type"],
            kotlinc_path=kotlinc,
            kotlin_stdlib_jars=kstd,
        )
        if not compiler.compile(self.config.src_dirs, gen_dir, deps_data["jars"], android_jar, classes_dir):
            return None
        for extra in compiler.extra_jars:
            if extra not in deps_data["jars"]:
                deps_data["jars"].append(extra)

        print(f"\n{Colors.CYAN}[5/7] Converting to DEX ({'R8' if use_r8 else 'D8'})...{Colors.RESET}")
        if use_r8:
            print(f"  {Colors.YELLOW}[WARN] R8 shrinking is ON. If the app dies on launch, rebuild with --d8.{Colors.RESET}")
        dexer = Dexer(tools["dexer_bin"], tools["dexer_type"], java_bin=self.toolchain.find_executable("java") or "java")

        with open(base_rules_path, "w", encoding="utf-8") as f:
            f.write(DEFAULT_BASE_PROGUARD)

        all_pg_rules: List[Path] = [base_rules_path]
        if aapt_rules_path.exists():
            all_pg_rules.append(aapt_rules_path)
        all_pg_rules.extend(deps_data["proguard_rules"])
        all_pg_rules.extend(self.config.proguard_rules)
        if use_r8:
            print(f"  [PROGUARD] Applied {len(all_pg_rules)} rule file(s).")
        else:
            print(f"  [D8] Shrinking off — {len(all_pg_rules)} ProGuard file(s) recorded, not passed to R8")

        if not dexer.dex(
            classes_dir=classes_dir,
            library_jars=deps_data["jars"],
            android_jar=android_jar,
            out_dir=dex_dir,
            min_sdk=self.config.min_sdk,
            use_r8=use_r8,
            proguard_rules=all_pg_rules,
            release=release,
        ):
            return None

        return {
            "deps_data": deps_data,
            "dex_dir": dex_dir,
            "linked": linked,
            "merged_manifest_path": merged_manifest_path,
        }

    def _add_tree_to_zip(self, apk_zip: zipfile.ZipFile, seen: Set[str], src_root: Path, arc_prefix: str, store_so: bool = False):
        if not src_root.exists():
            return
        for root, _, files in os.walk(str(src_root)):
            for fname in files:
                full_p = os.path.join(root, fname)
                rel_p = os.path.relpath(full_p, str(src_root)).replace("\\", "/")
                arc = f"{arc_prefix}/{rel_p}" if arc_prefix else rel_p
                if arc in seen:
                    continue
                seen.add(arc)
                compress = zipfile.ZIP_STORED if (store_so and fname.endswith(".so")) else zipfile.ZIP_DEFLATED
                apk_zip.write(full_p, arc, compress_type=compress)

    def _assemble_apk(self, base_apk: Path, deps_data: Dict[str, Any], dex_dir: Path, dest: Path):
        """Rebuild the APK from aapt2 output + DEX/assets/jni/services. Never append-in-place."""
        if dest.exists():
            dest.unlink()
        seen: Set[str] = set()
        with zipfile.ZipFile(str(base_apk), "r") as src, zipfile.ZipFile(str(dest), "w") as dst:
            for item in src.infolist():
                name = item.filename
                if name in seen:
                    continue
                # aapt2 sometimes emits a dummy classes.dex — we replace it.
                if name.startswith("classes") and name.endswith(".dex"):
                    continue
                seen.add(name)
                data = src.read(item.filename)
                dst.writestr(item, data)

            for dex_file in sorted(dex_dir.glob("classes*.dex")):
                if dex_file.name in seen:
                    continue
                seen.add(dex_file.name)
                dst.write(str(dex_file), dex_file.name, compress_type=zipfile.ZIP_DEFLATED)
            print(f"  [DEX] Injected {len(list(dex_dir.glob('classes*.dex')))} DEX file(s) into APK.")

            for adir in self.config.assets_dirs + deps_data["assets_dirs"]:
                self._add_tree_to_zip(dst, seen, adir, "assets")

            for jni_dir in self.config.jni_dirs + deps_data["jni_dirs"]:
                self._add_tree_to_zip(dst, seen, jni_dir, "lib", store_so=True)

            for svc_dir in deps_data.get("service_dirs") or []:
                self._add_tree_to_zip(dst, seen, svc_dir, "META-INF/services")

    def build_apk(self, release: bool = False, use_r8: bool = False) -> Optional[Path]:
        """Full automated pipeline to build and sign an APK."""
        print(f"\n{Colors.BOLD}{Colors.BLUE}=== Storm Build 2026 — APK ({'Release' if release else 'Debug'} | Target API: {self.config.target_sdk}) ==={Colors.RESET}")

        tools = self._require_tools(need_bundletool=False)
        if not tools:
            return None
        self.outputs_dir.mkdir(parents=True, exist_ok=True)

        prepared = self._prepare_code_and_resources(tools, proto=False, use_r8=use_r8, release=release)
        if not prepared:
            return None

        print(f"\n{Colors.CYAN}[6/7] Assembling APK Package (Assets & Native libs)...{Colors.RESET}")
        unaligned_apk = self.build_dir / "unaligned.apk"
        self._assemble_apk(prepared["linked"], prepared["deps_data"], prepared["dex_dir"], unaligned_apk)

        page_size = 16384 if self.config.target_sdk >= 35 else 4096
        print(f"\n{Colors.CYAN}[7/7] Aligning & Signing APK (Page align: {page_size // 1024}KB)...{Colors.RESET}")
        aligned_apk = self.build_dir / "aligned.apk"

        sys_zipalign = self.toolchain.get_zipalign()
        if sys_zipalign:
            print("  [ZIPALIGN] Using system zipalign binary...")
            z_res = subprocess.run([sys_zipalign, "-p", "-f", "4", str(unaligned_apk), str(aligned_apk)],
                                   stdout=subprocess.PIPE, stderr=subprocess.PIPE)
            if z_res.returncode != 0:
                print("  [ZIPALIGN] Falling back to Pure-Python ZipAligner...")
                align_apk(str(unaligned_apk), str(aligned_apk), alignment=4, page_align_so=True, page_size=page_size)
        else:
            print(f"  [ZIPALIGN] Using Pure-Python ZipAligner ({page_size // 1024}KB ARM64 alignment)...")
            align_apk(str(unaligned_apk), str(aligned_apk), alignment=4, page_align_so=True, page_size=page_size)

        is_aligned, _ = verify_alignment(str(aligned_apk), page_size=page_size)
        if not is_aligned:
            align_apk(str(unaligned_apk), str(aligned_apk), alignment=4, page_align_so=True, page_size=page_size)

        build_type = "release" if release else "debug"
        pf = self.config.active_flavor
        final_apk_name = f"{self.config.name}-{pf}-{build_type}.apk" if pf else f"{self.config.name}-{build_type}.apk"
        flavor = build_type
        final_apk = self.outputs_dir / final_apk_name

        signing_config = dict(self.config.signing.get(flavor, self.config.signing.get("debug", {})))
        signing_config["project_dir"] = str(self.root_dir)
        signing_config["flavor"] = flavor
        signer = Signer(
            apksigner_path=tools["signer_bin"],
            signer_type=tools["signer_type"],
            keytool_path=self.toolchain.find_executable("keytool") or "keytool",
            java_bin=self.toolchain.find_executable("java") or "java"
        )
        if not signer.sign_apk(aligned_apk, final_apk, signing_config):
            print(f"{Colors.RED}[ERROR] APK signing failed.{Colors.RESET}")
            return None

        has_yandex = any("yandex" in (d or "").lower() or "mobileads" in (d or "").lower()
                        for d in self.config.dependencies)
        print_apk_report(final_apk, self.config.package, has_yandex=has_yandex)

        print(f"\n{Colors.GREEN}{Colors.BOLD}✔ SUCCESS: APK created successfully!{Colors.RESET}")
        print(f"  📦 APK Location: {Colors.CYAN}{final_apk}{Colors.RESET}")
        print(f"  📏 Size: {final_apk.stat().st_size / (1024 * 1024):.2f} MB")
        print(f"  🔏 Signed as: {flavor} ({signing_config.get('keystore', 'debug.keystore')})")
        print(f"  🛡  Crash log (if the app dies): Android/data/{self.config.package}/files/storm_crash_log.txt")
        print(f"     also Downloads/storm_crash_log.txt and `storm logcat`")
        print("  💬 Chat / help:   https://t.me/wfllive_chat_base")
        print("  ❤  Support Storm: https://boosty.to/wfllive/donate\n")
        return final_apk

    def build_aab(self, release: bool = False, use_r8: bool = False) -> Optional[Path]:
        """Full pipeline to build an Android App Bundle (.aab)."""
        print(f"\n{Colors.BOLD}{Colors.BLUE}=== Storm Build 2026 — AAB (Target API: {self.config.target_sdk}) ==={Colors.RESET}")

        tools = self._require_tools(need_bundletool=True)
        if not tools:
            return None
        self.outputs_dir.mkdir(parents=True, exist_ok=True)

        prepared = self._prepare_code_and_resources(tools, proto=True, use_r8=use_r8, release=release)
        if not prepared:
            return None

        bundle_staging = self.build_dir / "bundle_staging"
        if bundle_staging.exists():
            shutil.rmtree(str(bundle_staging))
        bundle_staging.mkdir(parents=True, exist_ok=True)

        with zipfile.ZipFile(str(prepared["linked"]), "r") as pz:
            pz.extractall(str(bundle_staging))

        manifest_folder = bundle_staging / "manifest"
        manifest_folder.mkdir(parents=True, exist_ok=True)
        if (bundle_staging / "AndroidManifest.xml").exists():
            shutil.move(str(bundle_staging / "AndroidManifest.xml"), str(manifest_folder / "AndroidManifest.xml"))

        dex_folder = bundle_staging / "dex"
        dex_folder.mkdir(parents=True, exist_ok=True)
        for dex_file in prepared["dex_dir"].glob("classes*.dex"):
            shutil.copyfile(str(dex_file), str(dex_folder / dex_file.name))

        for jni_dir in self.config.jni_dirs + prepared["deps_data"]["jni_dirs"]:
            if jni_dir.exists():
                lib_dest = bundle_staging / "lib"
                lib_dest.mkdir(parents=True, exist_ok=True)
                for root, _, files in os.walk(str(jni_dir)):
                    for f in files:
                        if f.endswith(".so"):
                            full_p = os.path.join(root, f)
                            rel_p = os.path.relpath(full_p, str(jni_dir))
                            target_p = lib_dest / rel_p
                            target_p.parent.mkdir(parents=True, exist_ok=True)
                            shutil.copyfile(full_p, str(target_p))

        for adir in self.config.assets_dirs + prepared["deps_data"]["assets_dirs"]:
            if adir.exists():
                dest_assets = bundle_staging / "assets"
                dest_assets.mkdir(parents=True, exist_ok=True)
                for root, _, files in os.walk(str(adir)):
                    for f in files:
                        full_p = os.path.join(root, f)
                        rel_p = os.path.relpath(full_p, str(adir))
                        target_p = dest_assets / rel_p
                        target_p.parent.mkdir(parents=True, exist_ok=True)
                        if not target_p.exists():
                            shutil.copyfile(full_p, str(target_p))

        base_zip = self.build_dir / "base.zip"
        with zipfile.ZipFile(str(base_zip), "w", compression=zipfile.ZIP_DEFLATED) as bz:
            for root, _, files in os.walk(str(bundle_staging)):
                for f in files:
                    full_p = os.path.join(root, f)
                    rel_p = os.path.relpath(full_p, str(bundle_staging))
                    bz.write(full_p, rel_p)

        flavor = "release" if release else "debug"
        final_aab_name = f"{self.config.name}-{flavor}.aab"
        final_aab = self.outputs_dir / final_aab_name
        if final_aab.exists():
            final_aab.unlink()

        java_bin = self.toolchain.find_executable("java") or "java"
        bundletool = tools["bundletool"]
        if bundletool.endswith(".jar"):
            bt_cmd = [java_bin, "-jar", bundletool, "build-bundle", f"--modules={base_zip}", f"--output={final_aab}"]
        else:
            bt_cmd = [bundletool, "build-bundle", f"--modules={base_zip}", f"--output={final_aab}"]

        print("  [BUNDLETOOL] Generating .aab bundle...")
        bt_res = subprocess.run(bt_cmd, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
        if bt_res.returncode != 0:
            print(f"[ERROR] BundleTool failed:\n{bt_res.stderr}")
            return None

        signing_config = dict(self.config.signing.get(flavor, self.config.signing.get("debug", {})))
        signing_config["project_dir"] = str(self.root_dir)
        signing_config["flavor"] = flavor
        signer = Signer(java_bin=java_bin)
        signer.sign_aab(final_aab, signing_config)

        print(f"\n{Colors.GREEN}{Colors.BOLD}✔ SUCCESS: Android App Bundle (.aab) created successfully!{Colors.RESET}")
        print(f"  📦 AAB Location: {Colors.CYAN}{final_aab}{Colors.RESET}")
        print(f"  📏 Size: {final_aab.stat().st_size / (1024 * 1024):.2f} MB\n")
        return final_aab
