plugins {
  id 'com.android.library'
  id 'org.jetbrains.kotlin.android'
}

android {
  namespace "expo.modules.termuxterminal"
  compileSdkVersion 36

  defaultConfig {
    minSdkVersion 24
    targetSdkVersion 36

    externalNativeBuild {
      ndkBuild {
        arguments "APP_PLATFORM=android-24"
      }
    }

    ndk {
      abiFilters "arm64-v8a"
    }
  }

  externalNativeBuild {
    ndkBuild {
      path "src/main/jni/Android.mk"
    }
  }

  packaging {
    jniLibs {
      useLegacyPackaging = true
      keepDebugSymbols += [
        "**/libproot.so",
        "**/libproot-loader.so",
      ]
    }
  }

  compileOptions {
    sourceCompatibility JavaVersion.VERSION_17
    targetCompatibility JavaVersion.VERSION_17
  }

  kotlinOptions {
    jvmTarget = '17'
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3"
  implementation "com.google.android.material:material:1.12.0"
  implementation "androidx.annotation:annotation:1.8.2"
}