#!/usr/bin/env node
/**
 * Builds the WebView code editor (CodeMirror 6) into a single self-contained
 * HTML document and writes it as a JS module at src/ide/editorHtml.ts.
 *
 *   npm run editor
 *
 * The generated module is committed to the repo, so app builds do NOT need
 * this script — it is only required after changing files in web/.
 */
import esbuild from 'esbuild';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');

const result = await esbuild.build({
  entryPoints: [join(root, 'web/editor.js')],
  bundle: true,
  minify: true,
  format: 'iife',
  target: ['chrome78'], // Android System WebView baseline
  legalComments: 'none',
  logLevel: 'silent',
  write: false,
});

const js = result.outputFiles[0].text
  // never let the bundle close its own <script> tag
  .replace(/<\/script/gi, '<\\/script');

const html = readFileSync(join(root, 'web/index.html'), 'utf8')
  .replace('//__EDITOR_BUNDLE__', () => js);

const outDir = join(root, 'src/ide');
mkdirSync(outDir, { recursive: true });

const moduleSource =
  '/**\n' +
  ' * AUTO-GENERATED by scripts/build-editor.mjs — do not edit by hand.\n' +
  ' * Contains the complete offline CodeMirror IDE editor as an HTML document.\n' +
  ' */\n' +
  `export const EDITOR_HTML = ${JSON.stringify(html)};\n` +
  'export default EDITOR_HTML;\n';

writeFileSync(join(outDir, 'editorHtml.ts'), moduleSource);

const kb = (html.length / 1024).toFixed(1);
console.log(`[build-editor] wrote src/ide/editorHtml.ts (${kb} KB HTML, ${(js.length / 1024).toFixed(1)} KB JS)`);
